### ISSUE TITLE
Invalid contact data

### ISSUE THREAD

**Issue by strogonoff** [ietf-tools/relaton-data-ieee#12]
We get this:

https://github.com/ietf-tools/relaton-data-ieee/blob/08b9b484e65fcac7cbc7c0a7b9910bc0e98519e3/data/IEEE_P1896_D-2.4.2016.yaml#L32-L34

However, per spec, we expect something like:

```yaml
 contact: 
 - address:
     city: Piscataway 
     country: USA 
```
