### ISSUE TITLE
Why this repo clones itself?

### ISSUE THREAD

**Issue by andrew2net** [ietf-tools/relaton-data-ieee#20]
@stefanomunarini 
Before the [commit](https://github.com/ietf-tools/relaton-data-ieee/commit/759e8a74db11dce59c53ff6d5ca865d564764df1) this repo got documents from the private repo https://github.com/ietf-ribose/ieee-rawbib.
This GHA step [workflow](https://github.com/ietf-tools/relaton-data-ieee/commit/759e8a74db11dce59c53ff6d5ca865d564764df1#diff-73a5f52e43cc725cdeb8ed4080bba34f1f18762a041836c2cfea3e2241f4070a) checked out the source repo
```yaml
    ...
      - name: Checkout source
         uses: actions/checkout@v2
         with:
           repository: ietf-ribose/ieee-rawbib
           token: ${{ secrets.IETF_BIB_BOT_PAT }}
           path: ieee-rawbib
    ...
```
then the cloned data was converted to Relaton format
```yaml
    ...
      - name: Fetch documents
         run: |
           rm -rf data
           relaton fetch-data ieee-rawbib
    ...
```
In the commit a [crawler](https://github.com/ietf-tools/relaton-data-ieee/commit/759e8a74db11dce59c53ff6d5ca865d564764df1#diff-02c66de777b6d779342738052d48d06be8aa62d15ba1360b19166185a42e7659) is added, and the crawler clones the repo to itself.
```ruby
...
system("git clone https://github.com/ietf-tools/relaton-data-ieee")
...
```
I think this is a mistake.

**Comment by stefanomunarini** [comment]
Hi @andrew2net , thanks for reporting this. Are you suggesting that crawler should be cloning https://github.com/ietf-ribose/ieee-rawbib instead?

E.g. 

```
[...]
puts "Started at: #{t1}"

system("git clone https://github.com/ietf-ribose/ieee-rawbib")
FileUtils.rm_rf("data")
FileUtils.cp_r("relaton-data-ieee/data", ".")
[...]
```

In this case we would probably have to ask ietf-tools to also clone https://github.com/ietf-ribose/ieee-rawbib so that cloning can be done from https://github.com/ietf-tools/ieee-rawbib

**Comment by andrew2net** [comment]
Hi @stefanomunarini 

No, the crawler should not just clone the [ietf-ribose/ieee-rawbib](https://github.com/ietf-ribose/ieee-rawbib). It should temporary clone it into `ieee-rawbib` and run converter. In GHA we used the shell command `relaton fetch-data ieee-rawbib` to run the converter. But in the crawler using Ruby method `RelatonIeee::DataFetcher.fetch` is a better way. We shouldn't add the `ieee-rawbib` folded to commit as it is just temporary source data.

We don't need to ask ietf-tools to fork the `ieee-rawbib`. As you can see in GHA we used token to access the repo `token: ${{ secrets.IETF_BIB_BOT_PAT }}`. You can use the token in `git clone` command. Also, our goal is get updates from the `ieee-rawbib`, but fork won't be updated. Finally, IEEE wants the `ieee-rawbib` be private. So no forks possible.

**Comment by stefanomunarini** [comment]
Thanks @andrew2net . Amongst the secrets in https://github.com/ietf-ribose/relaton-data-ieee/settings/secrets/actions I cannot see ``secrets.IETF_BIB_BOT_PAT``. Which of the tokens listed in that page can be use to clone ietf-ribose/ieee-rawbib?

**Comment by andrew2net** [comment]
@stefanomunarini I don't have access to this repository's tokens. Maybe the token stored in the organization level. Ping @ronaldtse.
I also don't have access to  ietf-ribose/ieee-rawbib, but from previous GHA we can see that we just need to copy root level. There are not data/ or any other that we need to pick up. The previous GHA step that cloned ietf-ribose/ieee-rawbib was:
```yaml
    ...
      - name: Checkout source
         uses: actions/checkout@v2
         with:
           repository: ietf-ribose/ieee-rawbib
           token: ${{ secrets.IETF_BIB_BOT_PAT }}
           path: ieee-rawbib
    ...
```
it's equivalent to git command:
```
git clone https://<token>@github.com/ietf-ribose/ieee-rawbib.git ieee-rawbib
```
